name: ocr-benchmarking
channels:
  - defaults
dependencies:
  - aiofiles
  - anthropic
  - google-genai
  - instructor
  - jiwer
  - json-ref
  - openai
  - pandas
  - pillow
  - python
  - pydantic
  - pytesseract 
  - rapidfuzz
  - requests
  - typing
  


