name: ocr-benchmarking
channels:
  - defaults
dependencies:
  - python
  - pandas
  - rapidfuzz
  - pytesseract
  - anthropic
  - google-genai
  - openai
  - pillow
  - instructor
  - pydantic
  - typing
  - json-ref
  - jiwer
  - aiofiles
